"use client";
import "./globals.css";
import Header from "./header";
import Cookies from "js-cookie";
import { useRouter } from "next/navigation";
import { useState, useEffect, useCallback } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [isLoggedin, setIsLoggedin] = useState(false);

  useEffect(() => {
    const accessTokenRegex = /access_token=([^&]+)/;
    const isMatch = window.location.href.match(accessTokenRegex);

    if (isMatch) {
      setIsLoggedin(true);
    }
  }, []);

  useEffect(() => {
    setLoading(true);
    const accessToken = Cookies.get("access_token");
    if (!accessToken) {
      setIsLoggedin(false);
      router.push("/");
    } else {
      setIsLoggedin(true);
    }
    setLoading(false);
  }, [router]);

  const logout = useCallback(() => {
    Cookies.remove("access_token");
    setIsLoggedin(false);
    router.push("/");
  }, [router]);

  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen w-screen">
        <Header logout={logout} isLoggedin={isLoggedin} />
        {!loading && <main className="flex-1 p-12">{children}</main>}
      </body>
    </html>
  );
}
