import "./globals.css";
import Header from "./header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen w-screen">
        <Header />
        <main className="flex-1 flex items-center p-12">{children}</main>
      </body>
    </html>
  );
}
